### ISSUE TITLE
스타일 수정

### ISSUE THREAD

**Issue by min06150315** [LeeKyoungYoung/cra-web-frontend#33]
**Description**
- 헤더(소개), 헤더(메인), 리크루팅, 보드 리스트 스타일 수정

**Todo**
- [x] **보드 리스트 스타일 수정** (가독성 높이기 위해)
- [x] 소개 헤더 약간 수정
- [x] 메인 헤더 약간 수정
- [x] 리크루팅 페이지 약간 수정

**ETC**
- components/Board 디렉토리에서 구조 세분화
