### ISSUE TITLE
디자인 초안 보고 레이아웃 간단히 잡아놓기

### ISSUE THREAD

**Issue by min06150315** [LeeKyoungYoung/cra-web-frontend#34]
**Description**
- figma에 있는 디자인 초안대로 디자인 레이아웃 정도만 잡아놓기

**Todo**
- [x] 소개 페이지
- [x] 리크루팅 페이지
- [x] 메인 페이지
- [x] 로그인 페이지
- [x] 공지 게시판
- [x] 학술 게시판
- [ ] 학술 - 글쓰기 페이지
- [ ] 학술 - 게시글 페이지 (자세히 보기)
- [ ] 하브루타 게시판
- [ ] 하브루타 게시글 페이지
- [ ] 도서 게시판
- [ ] 비품 게시판
- [x] 기존 CSS -> Module CSS로 변경하기

**ETC**
- 그냥 TODO LIST, 커밋 X , 따로 이슈 파서 하기
- https://dev-ini.tistory.com/67 을 참고하여 CSS Module 사용해보기
