### ISSUE TITLE
Board CRUD: Detail & Update 기능 구현

### ISSUE THREAD

**Issue by min06150315** [LeeKyoungYoung/cra-web-frontend#38]
**Description**
- 게시판 자세히 보기, 수정 기능 구현

**Todo**
- [x] Board List에서 각 게시물 마다 Detail 페이지로 이동하는 버튼? 링크? 만들기
- [x] 어떠한 게시물의 Detail 버튼 눌렀을 때 그 게시물의 고유 id로 정보 서버에서 JSON 형식으로 받아오기
- [x] 서버에서 받아온 정보를 출력하기 위한 Detail 페이지 스타일링 하기
- [x] Update 폼으로 가는 버튼 추가하기 (Detail 페이지에 있어도 되고 List 페이지에 있어도 됨)
- [x] Update Form 이 있는 Update 페이지 구성하기 (+약간의 스타일)
- [x] Update 시에 빈 제출 폼이 아닌 기존의 입력 값들 가져와서 유저에게 보여줄수 있도록 구성
- [x] **Update Form 제출 내용 JSON 형식으로 서버로 보내기**

**ETC**
- 기타사항사항
