### ISSUE TITLE
Low level(main, App, Router) 구조 리팩토링

### ISSUE THREAD

**Issue by chanhk-im** [LeeKyoungYoung/cra-web-frontend#43]
**Description**
- Main, App, Router 코드 구조 수정 및 코드 리팩토링

**Todo**
- [x] Provider main.tsx에 몰아넣기
- [x] Header/Footer App으로 옮기기
- [ ] Router 유지 보수 용이하게 리팩토링(변수 사용, 계층 구조 추가)

**ETC**
- 제안을 목적으로 구현. 12/31 오전 회의때 논의할 예정
